drop table bucket;
drop table "order";
drop table Person;
create table Person(
                       id int generated by default as identity primary key ,
                       email varchar(100),
                       name varchar(100),
                       surname varchar(100),
                       password varchar,
                       role_id int references Role(role_id)

);
create table Role (
                      role_id int generated by default as identity primary key,
                      role_name varchar(100)

);
create table Sneakers(
                         sneakers_id int generated by default as identity primary key ,
                         name varchar(100),
                         price decimal,
                         about varchar(100),
                         image_path varchar(255) -- путь к файлу изображения на сервере
);
create table Bucket(
                       bucket_id int generated by default as identity primary key ,
                       user_id int references Person(id)  ,
                       sneakers_id int references Sneakers(sneakers_id)
);
create table "order"(
                        order_id int generated by default as identity primary key ,
                        user_id  int references Person(id),
                        address  varchar,
                        about    varchar
);

CREATE TABLE OrderDetails (
                              order_details_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              order_id INT REFERENCES "order"(order_id),
                              bucket_id INT REFERENCES Bucket(bucket_id)
);

-- Пример данных для таблицы Person
INSERT INTO Person (email, name, surname, password, role_id)
VALUES
    ('example1@example.com', 'John', 'Doe', 'password1', 1),
    ('example2@example.com', 'Jane', 'Smith', 'password2', 2),
    ('example3@example.com', 'Alice', 'Johnson', 'password3', 1);

-- Пример данных для таблицы Sneakers
INSERT INTO Sneakers (name, price, about, image_path)
VALUES
    ('Sneakers A', 99.99, 'Description of Sneakers A', '/images/sneakers_a.jpg'),
    ('Sneakers B', 129.99, 'Description of Sneakers B', '/images/sneakers_b.jpg'),
    ('Sneakers C', 79.99, 'Description of Sneakers C', '/images/sneakers_c.jpg');

-- Пример данных для таблицы Bucket
INSERT INTO Bucket (user_id, sneakers_id)
VALUES
    (1, 1),
    (1, 2),
    (2, 1),
    (3, 3);

-- Пример данных для таблицы Order
INSERT INTO "order" (user_id, address, about)
VALUES
    (1, '123 Main St', 'Order placed on 2024-03-06'),
    (2, '456 Elm St', 'Order placed on 2024-03-07'),
    (3, '789 Oak St', 'Order placed on 2024-03-08');

-- Пример данных для таблицы OrderDetails
INSERT INTO OrderDetails (order_id, bucket_id)
VALUES
    (1, 1),
    (1, 2),
    (2, 3),
    (3, 4);
ALTER TABLE bucket ADD COLUMN status BOOLEAN DEFAULT FALSE;